# Generated by Django 3.2.9 on 2021-11-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=25)),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=40)),
                ('bio', models.TextField()),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
    ]
