# Generated by Django 3.2.9 on 2021-11-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_initial',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
