# Generated by Django 3.2.9 on 2021-11-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211104_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='photos/headshots'),
        ),
        migrations.AlterField(
            model_name='member',
            name='github',
            field=models.URLField(blank=True, default='https://github.com/', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/', null=True),
        ),
    ]
