# Generated by Django 3.2.9 on 2021-11-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211104_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='photos/testimonials')),
                ('num_of_stars', models.FloatField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('quote', models.TextField(max_length=200)),
            ],
        ),
    ]
