# Generated by Django 3.2.9 on 2021-11-08 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(choices=[('1', '0-1000'), ('2', '1000-2000'), ('3', '2000-5000'), ('4', '5000-10k'), ('5', '10k+')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
