# Generated by Django 3.2.9 on 2021-11-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='budget',
            field=models.CharField(choices=[('web-tier1', '$1,000-2,000'), ('web-tier2', '$2,000-5,000'), ('web-tier3', '$5000-10,000'), ('web-tier4', '$10k+'), ('brand-tier1', '$200-500'), ('brand-tier2', '$500-1,000'), ('brand-tier3', '$1,000+')], max_length=50),
        ),
    ]
