# Generated by Django 3.2.9 on 2021-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cardTop',
            field=models.ImageField(blank=True, null=True, upload_to='photos/stories'),
        ),
        migrations.AlterField(
            model_name='story',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
