# Generated by Django 3.2.9 on 2021-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='organization',
            field=models.CharField(default='Orgnization Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='Story title', max_length=255),
        ),
    ]
