# Generated by Django 3.2.9 on 2021-11-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20211108_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='github',
            field=models.URLField(blank=True, default='https://github.com/', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='website',
            field=models.URLField(blank=True, default='https://thinkhalcyon.com/', null=True),
        ),
    ]
