# Generated by Django 3.2.9 on 2021-11-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20211114_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='excerpt',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.', max_length=200),
        ),
    ]
