# Generated by Django 3.2.9 on 2021-11-02 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
