# Generated by Django 3.2.9 on 2021-11-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False, null=True),
        ),
    ]
