# Generated by Django 3.2.9 on 2021-11-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211104_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='a1desc',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='a2desc',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='altDesc1',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='altDesc2',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='altDesc3',
            field=models.CharField(blank=True, default='Lorem ipsum dolor sit amet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author2HS',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog/profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='authorHS',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog/profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='bodyImage1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='bodyImage2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='cardTop',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog'),
        ),
        migrations.AddField(
            model_name='post',
            name='featuredImage',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog'),
        ),
    ]
