# Generated by Django 3.2.9 on 2021-11-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211104_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='a1desc',
            new_name='featDesc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='a2desc',
        ),
    ]
