# Generated by Django 3.2.9 on 2021-11-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20211107_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Business', 'Business'), ('Lifestyle', 'Lifestyle')], default='coding', max_length=100),
        ),
    ]
