# Generated by Django 3.2.9 on 2021-11-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_profile_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='photos/headshots'),
        ),
    ]
